name: Python CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html 
        pip install flake8
        pip install pygame
        pip install numpy

    - name: Run tests and create pytest report
      run: |
        pytest tests/ --html=reports/pytest_report/report.html
    
        - name: Create flake8 linter report
        run: |
          # Run flake8 and output HTML report
          mkdir -p reports/flake_report  # Create directory if not exists
          flake8 --format=html --extend-ignore=.venv,.github,pycache,.pytest_cache,assets,html --doctests --exclude=.venv,.github,pycache,.pytest_cache,assets,reports > reports/flake_report/flake_report.html
  
    - name: Upload flake8 HTML report
      uses: actions/upload-artifact@v2
      with:
        name: flake8-report
        path: reports/flake_report/flake_report.html